spring:
  profiles:
    include:
      - logger-${spring.profiles.active}
      - log-${spring.profiles.active}
    
server:
  servlet:
    context-path: /tech-app
  port: 8090
  #Change the default error mapping path from /error to /app/error
  error:
    path: /app/error
  
#Automatic Property Expansion Using Maven - '@project.name@' will read the value from pom.xml assign to variable project.name in yml file
maven:
  project:
    name: '@project.name@'
project:
  name: ${maven.project.name} Main
  version: '@project.version@'