 
#Automatic Property Expansion Using Maven - '@project.name@' will read the value from pom.xml assign to variable project.name in yml file
project:
  name: ${maven.project.name} Local
  version: '@project.version@'